version: '3.1'
services:
  db-dev:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: pomodoro_tests
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 4000:3306
  # backend:
  #   image: test
  #   restart: always
  #   env_file:
  #     - C:\Dev\pomodoro\apps\pomodoro-backend\.env
  #   ports:
  #     - 3000:3000


