version: '3.1'
services:
  test:
    container_name: test
    image: test-img
    restart: always
    volumes:
      - log:/log:rw
    tty: true
volumes:
  log:
    name: log
  front-build:
    name: front-build
  backend-build:
    name: backend-build
